[project]
name = "lama"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=6.0.2",
    "simple-lama-inpainting>=0.1.2",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
